### ISSUE TITLE
 node:internal/process/promises:227           triggerUncaughtException(err, true /* fromPromise */);

### ISSUE THREAD

**Issue by angelbotto** [pstevovski/express-app-cli#11]
I try to create diferent proyects but see this error.

![image](https://user-images.githubusercontent.com/266151/105643044-8c12a880-5e5b-11eb-9b18-330bfb942986.png)

**Comment by pstevovski** [comment]
@angelbotto Hi ! Sorry for replying 2 days later, for some reason I didn't even get a notification there was an open issue. Sorry about that.

Regarding the problem, there was a bug with getting the language template directory, when the project structure is selected trough prompting you the questions, like in your example  (instead of passing them as additional options), which is now **fixed**.

You'll need to update the package (either run `npm install -g express-app-cli` again, or delete it completely and then install it again), so hopefully that fixes the issue that happened here. If no, please come back at the issue and provide additional information.

Thanks :)
